### ISSUE TITLE
Missing attribute detail in _JSONError.

### ISSUE THREAD

**Issue by KoleS46** [mozilla-services/cornice#275]
```python
import logging
try:
    raise _JSONError('error')
except _JSONError as ex:
    logging.error(ex)

Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 846, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 723, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 324, in getMessage
    msg = str(self.msg)
  File "/home/laptop/.venv/system/local/lib/python2.7/site-packages/pyramid/httpexceptions.py", line 224, in __str__
    return self.detail or self.explanation
AttributeError: '_JSONError' object has no attribute 'detail'
```

The solution for this is to either initialize HTTPError from pyramid inside the __init__ method or maybe provide a local __str__method.
Or maybe I'm doing it wrong?

**Comment by ametaireau** [comment]
Depending on how you're using the exception, you might want to not do that, since it's private (starting with an _, and as such its signature may change in the future).

That being said, the way to solve this is probably to add attributes to the exception, as you're proposing. I'll gladly accept patches about that!
